version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  lint:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run: yarn lint

workflows:
  lint:
    jobs:
      - lint
